version: '3'

services: 
    flask_img:
        container_name: flask_app
        ports:
            - "80:5000"
        build:
            context: ./flask-app
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            # config:
            #     - subnet: ${NETWORK_SUBNET}