version: '3'
 
services:
    nginx_img:
        container_name: www_example_img
        ports: 
            - "80:80"
        build:
            context: ./nginx
        # networks:
        #     public_net:
        #         ipv4_address: ${NGINX_IP}
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            # config:
            #     - subnet: ${NETWORK_SUBNET}